// Centralized Data Mapping Configuration
// Used by both Node.js scripts (digest-data.js) and Client-side App

export const DATA_CONFIG = {
    // Input Files (Source of Truth)
    FILES: {
        TOP_300: 'Top 300 14_2_2026.xlsx', // Main stats file
        BANK: 'KD 97 Bank Ledger.xlsx', // Treasury data
        TROPHIES: 'Offseason_KingTrophies_2026.xlsx', // Historical data
        DEADWEIGHT: 'KD 97 Deadweight.xlsx' // Deadweight tracking
    },

    // Output JSON Files (Generated by script)
    JSON: {
        PLAYERS: 'players.json',
        HISTORY: 'kingdom_history.json',
        BANK: 'bank.json',
        DEADWEIGHT: 'deadweight.json',
        TROPHIES: 'trophies.json'
    },

    // Sheet Name Patterns (for fuzzy matching)
    SHEETS: {
        PLAYERS: 'AUTO', // 'AUTO' triggers automatic latest-tab detection (ignoring "Dashboard")
        KINGDOM_STATS: 'Dashboard',
        BANK_WEEKLY: 'Weekly Contribution',
        BANK_DASHBOARD: 'Dashboard',
        DEADWEIGHT: 'KD97 DW'
    },

    // Column Mappings (Header Names for Dynamic Parsing)
    PLAYER_COLUMNS: {
        ID: ['id', 'governor id'],
        NAME: ['name', 'governor', 'governor name'],
        POWER: ['power'],
        POWER_DIFF: ['power diff', 'power difference'],
        KP: ['kill points', 'killpoints', 'kp'],
        DEADS: ['dead', 'deads'],
        T1_KILLS: ['t1 kills', 't1'],
        T4_KILLS: ['t4 kills', 't4'],
        T5_KILLS: ['t5 kills', 't5'],
        RANGED: ['ranged', 'ranged pts', 'ranged points'],
        RSS_GATHERED: ['rss gathered', 'gathered'],
        RSS_ASSISTANCE: ['rss assistance', 'assistance'],
        HELPS: ['helps', 'help'],
        ALLIANCE: ['alliance', 'tag'],
        CITY_HALL: ['city hall', 'ch'],
        LOCATION: ['location', 'kingdom'],
        NOTES: ['notes', 'note']
    },

    // Kingdom History Columns (in Dashboard sheet)
    HISTORY_COLUMNS: {
        DATE: 1, // Column B
        POWER: 2, // Column C
        KP: 3 // Column D
    },

    // Bank Dashboard Rows (Fixed format)
    BANK_DASHBOARD: {
        ROWS: {
            FOOD: 1,
            WOOD: 2,
            STONE: 3,
            GOLD: 4
        },
        COL_INDEX: 3 // Column D
    },

    // Trophies - Vertical Parsing in V1
    // Week Title: "Week X..."
    // Trophy Type: Cell value (if not ID and not empty)
    // Structure is dynamic, so we just define the sheet name pattern here
    TROPHIES: {
        SHEET_PATTERN: 'List', // Actual sheet name in Offseason_KingTrophies_2026.xlsx
    },

    // Format « KD 2997 DW List » (2026-07-13) : onglet unique, plus de
    // Power Diff / KP Gained / Reason, colonne Highest Acclaim ajoutée.
    DEADWEIGHT: {
        SHEET_NAME: 'Arkusz1',
        COLUMNS: {
            ID: 0,
            NAME: 1,
            POWER: 2,
            KP: 3,
            ACCLAIM: 4,
            READY: 5,
            RSS_DONATION: 6,
            LOCATION: 7,
            PASSPORTS: 8,
            DATE_EMIGRATION: 9,
            NEED_KINGDOM: 10,
            ACCOUNT_AVAILABLE: 11,
            STATUS: 12,
            NOTE: 13,
            POWER_DIFF: -1, // absent du nouveau format
            KP_GAINED: -1,
            REASON: -1
        }
    },

    KVK: {
        FILE: 'SoC_4_KingOfAllBritain_2026.xlsx',
        TITLE: 'SoC 4: King of All Britain (2026)',
        SHEET_NAME: 'Performance Analysis',
        JSON_OUTPUT: 'kvk_stats.json',
        COLUMNS: {
            ID: 0,           // A: Governor ID
            NAME: 1,         // B: Name
            INITIAL_POWER: 2,// C: Initial Power
            FINAL_POWER: 3,  // D: Final Power
            INITIAL_KP: 4,   // E: Initial KP
            FINAL_KP: 5,     // F: Final KP
            TOTAL_KILLS: 6,  // G: Total Kills (NEW)
            TOTAL_DEAD: 7,   // H: Total Dead
            TOTAL_ACCLAIM: 8,// I: Total Acclaim (NEW)
            TOTAL_POWER_DIFF: 9, // J: Total Power Diff
            TOTAL_KP_GAINED: 10, // K: Total KP Gained
            GOAL_PERCENT: 14,    // O: % Goal
            GOAL_RATIO: 17,      // R: Goal Ratio
            RATE: 18             // S: Rate
        }
    },

    KVK_FILLER: {
        SHEET_NAME: 'Filler Accounts',
        COLUMNS: {
            ID: 0, // A
            NAME: 1, // B
            INITIAL_POWER: 2, // C
            FINAL_POWER: 6, // G
            KP: 3, // D
            T4_DEAD: 12, // M
            T5_DEAD: 13, // N
            PASS4_DEAD: 14, // O
            // PASS7_DEAD: 15,
            KL_DEAD: 15, // P
            TOTAL_DEAD: 16, // Q
            GOAL_PERCENT: 19 // T: %Goal (col 18/S is %min Dead)
        }
    },

    // Google Sheets Configuration (for Cloud Functions)
    GOOGLE_SHEETS: {
        PLAYERS: {
            SPREADSHEET_ID: "1JS1nzH14YOmFxJcXN2oURXOKcvtqbxUGPFJebNTj63E"
        },
        BANK: {
            SPREADSHEET_ID: "1Al6LMeFEKEiMdRFsDTuogFe7ryDWAVxBAEFzSJ8rAYg"
        },
        TROPHIES: {
            SPREADSHEET_ID: "1vT3dDPogf4rMLah2sRzTuJxx56AlHOb64ZVRaR1Kfmo"
        },
        DEADWEIGHT: {
            SPREADSHEET_ID: "1Cj_2fwkhwGD9az6Ir3Y3dI-EgQvPbr84wPAES4S9nuo" // KD 2997 DW List 13/07/2026
        },
        KVK: {
            SPREADSHEET_ID: "1qX6b4Z6w70x5gbk63aACVLU3QSNMHDWFo0QO1a7hy3A"
        }
    },

    // Fresh in-game avatar URLs (Lilith CDN) relayed by ProKingdoms' public
    // KvK endpoint — see docs/pm/Etude_Avatars_Joueurs.md.
    PROKINGDOMS: {
        KVK_MAP_ID: "1249539", // current KvK map — update each season (null disables the pass)
        KINGDOM_ID: 2997,
        MAX_PAGES: 8,          // ~429 rate limit beyond this in one burst
        PAGE_DELAY_MS: 2500
    }
};
