// Centralized Data Mapping Configuration
// Used by both Node.js scripts (digest-data.js) and Client-side App

export const DATA_CONFIG = {
    // Input Files (Source of Truth)
    FILES: {
        TOP_300: 'Top 300 14_2_2026.xlsx', // Main stats file
        BANK: 'KD 97 Bank Ledger.xlsx', // Treasury data
        TROPHIES: 'Offseason_KingTrophies_2026.xlsx', // Historical data
        DEADWEIGHT: 'KD 97 Deadweight.xlsx' // Deadweight tracking
    },

    // Output JSON Files (Generated by script)
    JSON: {
        PLAYERS: 'players.json',
        HISTORY: 'kingdom_history.json',
        BANK: 'bank.json',
        DEADWEIGHT: 'deadweight.json',
        TROPHIES: 'trophies.json'
    },

    // Sheet Name Patterns (for fuzzy matching)
    SHEETS: {
        PLAYERS: '14_2', // Matches "14_2_2026"
        KINGDOM_STATS: 'Dashboard',
        BANK_WEEKLY: 'Weekly Contribution',
        BANK_DASHBOARD: 'Dashboard',
        DEADWEIGHT: 'KD97 DW'
    },

    // Column Mappings (Indices)
    PLAYER_COLUMNS: {
        ID: 0,
        NAME: 1,
        POWER: 2,
        POWER_DIFF: 3,
        KP: 4,
        DEADS: 5,
        T1_KILLS: 6,
        T4_KILLS: 7,
        T5_KILLS: 8,
        RANGED: 9,
        RSS_GATHERED: 10,
        RSS_ASSISTANCE: 11,
        HELPS: 12,
        ALLIANCE: 13,
        CITY_HALL: 14,
        LOCATION: 15,
        NOTES: 16
    },

    // Kingdom History Columns (in Dashboard sheet)
    HISTORY_COLUMNS: {
        DATE: 1, // Column B
        POWER: 2, // Column C
        KP: 3 // Column D
    },

    // Bank Dashboard Rows (Fixed format)
    BANK_DASHBOARD: {
        ROWS: {
            FOOD: 1,
            WOOD: 2,
            STONE: 3,
            GOLD: 4
        },
        COL_INDEX: 3 // Column D
    },

    // Trophies - Vertical Parsing in V1
    // Week Title: "Week X..."
    // Trophy Type: Cell value (if not ID and not empty)
    // Structure is dynamic, so we just define the sheet name pattern here
    TROPHIES: {
        SHEET_PATTERN: 'List', // Actual sheet name in Offseason_KingTrophies_2026.xlsx
    },

    DEADWEIGHT: {
        SHEET_NAME: 'KD97 DW',
        COLUMNS: {
            ID: 0,
            NAME: 1,
            POWER: 2,
            KP: 3,
            POWER_DIFF: 4,
            KP_GAINED: 5,
            REASON: 6,
            READY: 7,
            RSS_DONATION: 8,
            LOCATION: 9,
            PASSPORTS: 10,
            DATE_EMIGRATION: 11,
            NEED_KINGDOM: 12,
            ACCOUNT_AVAILABLE: 13,
            STATUS: 14,
            NOTE: 15
        }
    },

    KVK: {
        FILE: 'SoC_2_StormOfStratagems_2025.xlsx',
        SHEET_NAME: 'Performance Analysis',
        JSON_OUTPUT: 'kvk_stats.json',
        COLUMNS: {
            ID: 0,
            NAME: 1,
            INITIAL_POWER: 2,
            FINAL_POWER: 3,
            INITIAL_KP: 4,
            FINAL_KP: 5,
            TOTAL_DEAD: 8,
            TOTAL_POWER_DIFF: 9,
            TOTAL_KP_GAINED: 10,
            GOAL_PERCENT: 14,
            RATE: 18
        }
    }
};
