/**
 * v2 iconography — Phosphor (see Claude Design v2/foundations/iconography.html).
 * Compat module: re-exports Phosphor icons under the legacy lucide-react names
 * so call sites only change their import path. Weights: regular by default,
 * pass weight="fill" for active states, weight="duotone" for statcard bubbles.
 * Sizes: 16 inline/table · 20 nav & buttons · 24 statcard bubbles.
 */
export {
    PulseIcon as Activity,
    WarningCircleIcon as AlertCircle,
    WarningIcon as AlertTriangle,
    ArchiveIcon as Archive,
    ArrowDownIcon as ArrowDown,
    ArrowRightIcon as ArrowRight,
    ArrowUpIcon as ArrowUp,
    ArrowsDownUpIcon as ArrowUpDown,
    MedalIcon as Award,
    CalendarIcon as Calendar,
    CheckCircleIcon as CheckCircle,
    CheckCircleIcon as CheckCircle2,
    CaretDownIcon as ChevronDown,
    CaretLeftIcon as ChevronLeft,
    CaretRightIcon as ChevronRight,
    CaretUpIcon as ChevronUp,
    RadioButtonIcon as CircleDot,
    ClockIcon as Clock,
    CoinIcon as Coin,
    CoinsIcon as Coins,
    CrownIcon as Crown,
    CubeIcon as Cube,
    GrainsIcon as Grains,
    DatabaseIcon as Database,
    FileXlsIcon as FileSpreadsheet,
    FunnelIcon as Filter,
    GlobeIcon as Globe,
    ClockCounterClockwiseIcon as History,
    SquaresFourIcon as LayoutDashboard,
    SignInIcon as LogIn,
    SignOutIcon as LogOut,
    MedalIcon as Medal,
    ListIcon as Menu,
    MoonIcon as Moon,
    AirplaneIcon as Plane,
    ArrowsClockwiseIcon as RefreshCw,
    FloppyDiskIcon as Save,
    MagnifyingGlassIcon as Search,
    ShieldIcon as Shield,
    ShieldWarningIcon as ShieldAlert,
    SkullIcon as Skull,
    SunIcon as Sun,
    SwordIcon as Sword,
    SwordIcon as Swords,
    TreeIcon as Trees,
    TrendDownIcon as TrendingDown,
    TrendUpIcon as TrendingUp,
    TrophyIcon as Trophy,
    UploadSimpleIcon as Upload,
    UserIcon as User,
    UserMinusIcon as UserX,
    UsersIcon as Users,
    WalletIcon as Wallet,
    XIcon as X,
    XCircleIcon as XCircle,
    LightningIcon as Zap,
    MapPinIcon as MapPin,
    HammerIcon as Hammer,
    ScrollIcon as ScrollText,
    // Domain mapping (v2) — new canonical names for nav surfaces
    HouseIcon as House,
    CastleTurretIcon as CastleTurret,
    BankIcon as Bank,
    TargetIcon as Target,
    FlagIcon as Flag,
    UsersThreeIcon as UsersThree,
} from '@phosphor-icons/react';
